"'Product Screen' As screen":
    Fill: =RGBA(29, 29, 29, 1)
    LoadingSpinnerColor: =RGBA(100, 118, 132, 1)

    "Gallery2 As gallery.'BrowseLayout_Horizontal_TwoTextOneImageVariant_ver4.0'":
        BorderColor: =RGBA(197, 203, 207, 1)
        Items: =Products
        OnSelect: |-
            =Set(varCurrentProductRecord, ThisItem);
            EditForm(frm_CCDProdDetails);
            Navigate('CCD Product Details');
        TemplatePadding: =0
        TemplateSize: =Min(440, Self.Height - 60)
        Width: =1350
        Y: =177
        ZIndex: =1

        Image4 As image:
            BorderColor: =RGBA(197, 203, 207, 1)
            DisabledBorderColor: =RGBA(166, 166, 166, 1)
            DisabledFill: =RGBA(244, 244, 244, 1)
            Height: =276
            Image: =ThisItem.'Product Image'
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth - 32
            X: =(Parent.TemplateWidth / 2) - (Self.Width / 2)
            Y: =16
            ZIndex: =1

        Title2 As label:
            Align: =Align.Center
            Color: =RGBA(255, 255, 255, 1)
            DisabledColor: =RGBA(166, 166, 166, 1)
            FontWeight: =FontWeight.Semibold
            Height: =Self.Size * 1.8
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =20
            Text: =ThisItem.Name
            VerticalAlign: =VerticalAlign.Top
            Width: =Parent.TemplateWidth - 64
            X: =32
            Y: =Image4.Y + Image4.Height + 16
            ZIndex: =2

        Subtitle2 As label:
            Align: =Align.Center
            Color: =RGBA(255, 255, 255, 1)
            DisabledColor: =RGBA(166, 166, 166, 1)
            Height: =Self.Size * 1.8
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Size: =18
            Text: ="$" & Text(ThisItem.Price,"0.00")
            VerticalAlign: =VerticalAlign.Top
            Width: =Title2.Width
            X: =Title2.X
            Y: =Title2.Y + Title2.Height + 8
            ZIndex: =3

        Button1 As button:
            DisabledBorderColor: =RGBA(166, 166, 166, 1)
            DisabledColor: =RGBA(166, 166, 166, 1)
            DisabledFill: =RGBA(244, 244, 244, 1)
            Fill: =RGBA(100, 118, 132, 1)
            FontWeight: =FontWeight.Semibold
            Height: =42
            HoverColor: =RGBA(255, 255, 255, 1)
            HoverFill: =ColorFade(RGBA(100, 118, 132, 1), -20%)
            OnSelect: |-
                =Collect(ShoppingCart,{Name: ThisItem.Name, Price: ThisItem.Price})
            Size: =15
            Text: ="Add To Cart"
            X: =162
            Y: =477
            ZIndex: =4

    Label2 As label:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        FontWeight: =FontWeight.Bold
        Size: =25
        Text: ="PRODUCTS"
        Width: =210
        X: =56
        Y: =133
        ZIndex: =2

    cmp_ccd_top_nav_1 As cmp_ccd_top_nav:
        Height: =129
        Width: =1366
        ZIndex: =3

